# Generated by Django 4.0 on 2022-11-09 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0002_clienttrainer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clienttrainer',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_client', to='auth.user', unique=True),
        ),
    ]
