# Generated by Django 4.0 on 2022-11-18 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0003_alter_clienttrainer_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clienttrainer',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='T_assigned_client', to='auth.user', unique=True),
        ),
        migrations.AlterField(
            model_name='clienttrainer',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='T_assigned_trainer', to='auth.user'),
        ),
        migrations.CreateModel(
            name='clientDieter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='D_assigned_client', to='auth.user', unique=True)),
                ('dieter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='D_assigned_dietician', to='auth.user')),
            ],
        ),
    ]
