# Generated by Django 4.0 on 2022-12-07 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0004_alter_clienttrainer_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdieter',
            name='client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='D_assigned_client', to='auth.user'),
        ),
        migrations.AlterField(
            model_name='clientdieter',
            name='dieter',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='D_assigned_dietician', to='auth.user'),
        ),
        migrations.AlterField(
            model_name='clienttrainer',
            name='client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='T_assigned_client', to='auth.user'),
        ),
        migrations.AlterField(
            model_name='clienttrainer',
            name='trainer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='T_assigned_trainer', to='auth.user'),
        ),
    ]
