# Generated by Django 4.1.2 on 2022-12-13 01:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workout_type', models.CharField(choices=[('Cardio', 'Cardio'), ('Strength', 'Strength'), ('Endurance', 'Endurance')], max_length=50)),
                ('muscle_group', models.CharField(choices=[('Arms', 'Arms'), ('Shoulders', 'Shoulders'), ('Back', 'Back'), ('Core', 'Core'), ('Legs', 'Legs')], max_length=50)),
                ('exercise_name', models.CharField(max_length=50)),
                ('reps', models.IntegerField()),
                ('sets', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='clientTrainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_trainer_client', to=settings.AUTH_USER_MODEL)),
                ('trainer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_trainer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
