# Generated by Django 4.0 on 2022-11-15 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0002_alter_workout_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='muscle_group',
            field=models.CharField(choices=[('Arms', 'Arms'), ('Shoulders', 'Shoulders'), ('Back', 'Back'), ('Core', 'Core'), ('Legs', 'Legs')], max_length=50),
        ),
        migrations.AlterField(
            model_name='workout',
            name='workout_type',
            field=models.CharField(choices=[('Cardio', 'Cardio'), ('Strength', 'Strength'), ('Endurance', 'Endurance')], max_length=50),
        ),
    ]
