# Generated by Django 4.0 on 2022-11-18 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0003_alter_workout_muscle_group_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TrainerProfile',
        ),
    ]
