<<<<<<< HEAD
# Generated by Django 4.1.2 on 2022-11-16 18:48

import diet.models
from django.conf import settings
=======
# Generated by Django 4.0 on 2022-11-15 23:54

import diet.models
>>>>>>> c574f98d1de5daed559251a8c9480db91e6b8667
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
=======
        ('auth', '0012_alter_user_first_name_max_length'),
>>>>>>> c574f98d1de5daed559251a8c9480db91e6b8667
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='Revenue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MonthlyRevenue', models.CharField(max_length=50)),
                ('Month', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
=======
>>>>>>> c574f98d1de5daed559251a8c9480db91e6b8667
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_name', models.CharField(max_length=100)),
                ('meal_type', models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner'), ('Snack', 'Snack')], max_length=50)),
                ('calories', models.IntegerField()),
                ('carbs', models.IntegerField()),
                ('sugars', models.IntegerField()),
                ('protein', models.IntegerField()),
<<<<<<< HEAD
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
=======
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
>>>>>>> c574f98d1de5daed559251a8c9480db91e6b8667
            ],
        ),
        migrations.CreateModel(
            name='DietitianProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='John', max_length=100)),
                ('last_name', models.CharField(default='Doe', max_length=100)),
                ('dob', models.DateField(max_length=8, validators=[diet.models.validate_dob], verbose_name='birthdate')),
                ('email', models.EmailField(max_length=200, null=True)),
                ('bio', models.TextField(blank=True, max_length=500)),
<<<<<<< HEAD
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
=======
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
>>>>>>> c574f98d1de5daed559251a8c9480db91e6b8667
            ],
        ),
    ]
