# Generated by Django 4.1.1 on 2022-10-24 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meal',
            old_name='user_id',
            new_name='user',
        ),
    ]
