# Generated by Django 4.1.1 on 2022-10-10 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack')], max_length=50)),
                ('calories', models.IntegerField()),
                ('carbs', models.IntegerField()),
                ('sugars', models.IntegerField()),
                ('protein', models.IntegerField()),
            ],
        ),
    ]
