# Generated by Django 4.0 on 2022-11-18 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0002_alter_meal_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DietitianProfile',
        ),
    ]
