# Generated by Django 4.1.1 on 2022-12-07 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0002_alter_meal_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='created_at',
            field=models.DateTimeField(default='2006-10-25 14:30:59'),
        ),
    ]
