# Generated by Django 4.1.2 on 2022-12-01 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0002_alter_meal_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Revenue',
        ),
    ]
