# Generated by Django 4.0 on 2022-12-07 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('diet', '0004_clientdieter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdieter',
            name='client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_diet_client', to='auth.user'),
        ),
        migrations.AlterField(
            model_name='clientdieter',
            name='dieter',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_dietician', to='auth.user'),
        ),
    ]
