# Generated by Django 4.0 on 2022-12-08 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0003_delete_revenue_meal_created_at'),
        ('diet', '0005_alter_clientdieter_client_alter_clientdieter_dieter'),
    ]

    operations = [
    ]
